import numpy as np
# from typing import List

from exceptions import OceanSDKException

def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """ Returns distance in km using haversine method

    Args:
        lat1 (float): Coordinate in decimal degrees
        lon1 (float): Coordinate in decimal degrees
        lat2 (float): Coordinate in decimal degrees
        lon2 (float): Coordinate in decimal degrees

    Returns:
        float: Returns great circle distance in km
    """
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    # Calculate deltas
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    # Haversine method for measuring distance on a sphere
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    km = 6367 * c
    return km

def nearest_station(category: str, lat: float, lon: float) -> str:
    """Returns nearest station from list

    Args:
        category (str): Measurement category for switching data source
            [tide]
        lat (float): Coordinate in decimal degrees
        lon (float): Coordinate in decimal degrees

    Raises:
        KeyError: _description_
        
    Returns:
        str: Unique station ID
    """
    # Select measurement category and return dict of stations
    try:
        if 'tide' in category.lower():
            stations = noaa_tide_stations
        else:
            pass
    except (KeyError) as e:
        raise OceanSDKException("No Category found") from e

    # Find station closest to input coordinates using haversine
    # and is also active for water level
    min = float('inf') # Initialize minimum pointer
    for k,v in stations.items():
        new_val = haversine(lat, lon, v['lat'], v['lon'])
        # todo: AND is active
        if new_val < min:
            min = new_val
            min_key = k
    return min_key


# Generated from https://opendap.co-ops.nos.noaa.gov/stations/stationsXML.jsp (Jun 1 2022)
noaa_tide_stations = {
    "1611400": {
        'name': "Nawiliwili",
        'lat': 21.9544,
        'lon': -159.3561,
        'state': 'HI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "1612340": {
        'name': "Honolulu",
        'lat': 21.3067,
        'lon': -157.867,
        'state': 'HI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "1612480": {
        'name': "Mokuoloe",
        'lat': 21.4331,
        'lon': -157.79,
        'state': 'HI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "1615680": {
        'name': "Kahului, Kahului Harbor",
        'lat': 20.895,
        'lon': -156.4767,
        'state': 'HI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "1617433": {
        'name': "Kawaihae",
        'lat': 20.0366,
        'lon': -155.8294,
        'state': 'HI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "1617760": {
        'name': "Hilo, Hilo Bay, Kuhio Bay",
        'lat': 19.7303,
        'lon': -155.06,
        'state': 'HI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "1619910": {
        'name': "Sand Island, Midway Islands",
        'lat': 28.2117,
        'lon': -177.36,
        'state': 'United States of America',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "1630000": {
        'name': "Apra Harbor, Guam",
        'lat': 13.4434,
        'lon': 144.6564,
        'state': 'United States of America',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "1631428": {
        'name': "Pago Bay, Guam",
        'lat': 13.4283,
        'lon': 144.7969,
        'state': 'United States of America',
        "Winds": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "1770000": {
        'name': "Pago Pago, American Samoa",
        'lat': -14.2767,
        'lon': -170.6894,
        'state': 'American Samoa',
        "Water Level": "1",
        },
    "1820000": {
        'name': "Kwajalein, Marshall Islands",
        'lat': 8.7317,
        'lon': 167.7361,
        'state': 'United States of America',
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "1890000": {
        'name': "Wake Island, Pacific Ocean",
        'lat': 19.2906,
        'lon': 166.6175,
        'state': 'United States of America',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "2695535": {
        'name': "Bermuda Biological Station",
        'lat': 32.37,
        'lon': -64.695,
        'state': '',
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Water Level": "1",
        },
    "2695540": {
        'name': "Bermuda, St. Georges Island",
        'lat': 32.3733,
        'lon': -64.7033,
        'state': 'Bermuda',
        "Winds": "0",
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Water Level": "0",
        },
    "8311030": {
        'name': "Ogdensburg",
        'lat': 44.7017,
        'lon': -75.494,
        'state': 'NY',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8311062": {
        'name': "Alexandria Bay",
        'lat': 44.3311,
        'lon': -75.9345,
        'state': 'NY',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8410140": {
        'name': "Eastport",
        'lat': 44.9046,
        'lon': -66.9829,
        'state': 'ME',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8411060": {
        'name': "Cutler Farris Wharf",
        'lat': 44.657,
        'lon': -67.2047,
        'state': 'ME',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8413320": {
        'name': "Bar Harbor",
        'lat': 44.3922,
        'lon': -68.2043,
        'state': 'ME',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8418150": {
        'name': "Portland",
        'lat': 43.6581,
        'lon': -70.2442,
        'state': 'ME',
        "Air Temp": "1",
        "Water Temp": "1",
        "Water Level": "1",
        },
    "8419317": {
        'name': "Wells",
        'lat': 43.32,
        'lon': -70.5633,
        'state': 'ME',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8419870": {
        'name': "Seavey Island",
        'lat': 43.0797,
        'lon': -70.741,
        'state': 'ME',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "8443970": {
        'name': "Boston",
        'lat': 42.3539,
        'lon': -71.0503,
        'state': 'MA',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8447386": {
        'name': "Fall River",
        'lat': 41.7043,
        'lon': -71.1641,
        'state': 'MA',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8447387": {
        'name': "Borden Flats Light at Fall River",
        'lat': 41.705,
        'lon': -71.1733,
        'state': 'MA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8447412": {
        'name': "Fall River Visibility",
        'lat': 41.6958,
        'lon': -71.1798,
        'state': 'MA',
        "Air Temp": "0",
        "Visibility": "0",
        "Humidity": "0",
        },
    "8447435": {
        'name': "Chatham, Lydia Cove",
        'lat': 41.6881,
        'lon': -69.9508,
        'state': 'MA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8447930": {
        'name': "Woods Hole",
        'lat': 41.5236,
        'lon': -70.6711,
        'state': 'MA',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8449130": {
        'name': "Nantucket Island",
        'lat': 41.2853,
        'lon': -70.0964,
        'state': 'MA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8452314": {
        'name': "Sandy Point Visibility, Prudence Island",
        'lat': 41.6051,
        'lon': -71.3042,
        'state': 'RI',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8452660": {
        'name': "Newport",
        'lat': 41.5043,
        'lon': -71.3261,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Water Level": "1",
        },
    "8452944": {
        'name': "Conimicut Light",
        'lat': 41.7167,
        'lon': -71.3433,
        'state': 'RI',
        "Winds": "0",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8452951": {
        'name': "Potter Cove, Prudence Island",
        'lat': 41.6372,
        'lon': -71.3393,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8453662": {
        'name': "Providence Visibility",
        'lat': 41.7857,
        'lon': -71.3831,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "0",
        },
    "8454000": {
        'name': "Providence",
        'lat': 41.8071,
        'lon': -71.4012,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8454049": {
        'name': "Quonset Point",
        'lat': 41.5869,
        'lon': -71.41,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Water Level": "1",
        },
    "8454123": {
        'name': "Port of Davisville",
        'lat': 41.6112,
        'lon': -71.4103,
        'state': 'RI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        },
    "8461490": {
        'name': "New London",
        'lat': 41.3717,
        'lon': -72.0955,
        'state': 'CT',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8465705": {
        'name': "New Haven",
        'lat': 41.2833,
        'lon': -72.9083,
        'state': 'CT',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8467150": {
        'name': "Bridgeport",
        'lat': 41.1733,
        'lon': -73.1817,
        'state': 'CT',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8510560": {
        'name': "Montauk",
        'lat': 41.0483,
        'lon': -71.9594,
        'state': 'NY',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8516945": {
        'name': "Kings Point",
        'lat': 40.8103,
        'lon': -73.765,
        'state': 'NY',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8517986": {
        'name': "Verrazano-Narrows Air Gap",
        'lat': 40.6062,
        'lon': -74.0448,
        'state': 'NY',
        "Air Gap": "1",
        },
    "8518750": {
        'name': "The Battery",
        'lat': 40.7006,
        'lon': -74.0142,
        'state': 'NY',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8518962": {
        'name': "Turkey Point Hudson River NERRS",
        'lat': 42.0142,
        'lon': -73.9392,
        'state': 'NY',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        "Humidity": "1",
        },
    "8519461": {
        'name': "Bayonne Bridge Air Gap",
        'lat': 40.6419,
        'lon': -74.1414,
        'state': 'NY',
        "Air Gap": "1",
        },
    "8519483": {
        'name': "Bergen Point West Reach",
        'lat': 40.6391,
        'lon': -74.1463,
        'state': 'NY',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8519532": {
        'name': "Mariners Harbor",
        'lat': 40.6383,
        'lon': -74.16,
        'state': 'NY',
        "Winds": "1",
        },
    "8530973": {
        'name': "Robbins Reef",
        'lat': 40.6567,
        'lon': -74.065,
        'state': 'NJ',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8531680": {
        'name': "Sandy Hook",
        'lat': 40.4669,
        'lon': -74.0094,
        'state': 'NJ',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8534720": {
        'name': "Atlantic City",
        'lat': 39.3567,
        'lon': -74.4181,
        'state': 'NJ',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8536110": {
        'name': "Cape May",
        'lat': 38.9683,
        'lon': -74.96,
        'state': 'NJ',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8537121": {
        'name': "Ship John Shoal",
        'lat': 39.305,
        'lon': -75.375,
        'state': 'NJ',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8539094": {
        'name': "Burlington, Delaware River",
        'lat': 40.0817,
        'lon': -74.8697,
        'state': 'NJ',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8540433": {
        'name': "Marcus Hook",
        'lat': 39.8117,
        'lon': -75.4094,
        'state': 'PA',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8545240": {
        'name': "Philadelphia",
        'lat': 39.9333,
        'lon': -75.1417,
        'state': 'PA',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8545556": {
        'name': "Ben Franklin Bridge Air Gap",
        'lat': 39.9528,
        'lon': -75.1358,
        'state': 'PA',
        "Air Gap": "1",
        },
    "8546252": {
        'name': "Bridesburg",
        'lat': 39.9833,
        'lon': -75.075,
        'state': 'PA',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8548989": {
        'name': "Newbold",
        'lat': 40.1367,
        'lon': -74.7517,
        'state': 'PA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8550959": {
        'name': "Delaware Memorial Bridge Air Gap",
        'lat': 39.6883,
        'lon': -75.5183,
        'state': 'DE',
        "Air Gap": "1",
        },
    "8551762": {
        'name': "Delaware City",
        'lat': 39.5817,
        'lon': -75.5883,
        'state': 'DE',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8551910": {
        'name': "Reedy Point",
        'lat': 39.5583,
        'lon': -75.5719,
        'state': 'DE',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8551911": {
        'name': "Reedy Point Air Gap",
        'lat': 39.5583,
        'lon': -75.5824,
        'state': 'DE',
        "Air Gap": "1",
        },
    "8555889": {
        'name': "Brandywine Shoal Light",
        'lat': 38.987,
        'lon': -75.113,
        'state': 'DE',
        "Winds": "1",
        "Air Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8557380": {
        'name': "Lewes",
        'lat': 38.7817,
        'lon': -75.12,
        'state': 'DE',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8570283": {
        'name': "Ocean City Inlet",
        'lat': 38.3283,
        'lon': -75.0911,
        'state': 'MD',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8571421": {
        'name': "Bishops Head",
        'lat': 38.22,
        'lon': -76.0383,
        'state': 'MD',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8571892": {
        'name': "Cambridge",
        'lat': 38.5725,
        'lon': -76.0617,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8573364": {
        'name': "Tolchester Beach",
        'lat': 39.2133,
        'lon': -76.245,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8573927": {
        'name': "Chesapeake City",
        'lat': 39.5267,
        'lon': -75.81,
        'state': 'MD',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8573928": {
        'name': "Chesapeake City Air Gap",
        'lat': 39.5267,
        'lon': -75.81,
        'state': 'MD',
        "Air Gap": "1",
        },
    "8574680": {
        'name': "Baltimore",
        'lat': 39.2669,
        'lon': -76.5794,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "0",
        "Water Level": "1",
        },
    "8574728": {
        'name': "Francis Scott Key Bridge",
        'lat': 39.22,
        'lon': -76.5283,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8574729": {
        'name': "Francis Scott Key Bridge N.E. Tower",
        'lat': 39.22,
        'lon': -76.525,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8574730": {
        'name': "Francis Scott Key Bridge Air Gap",
        'lat': 39.2172,
        'lon': -76.5281,
        'state': 'MD',
        "Air Gap": "1",
        },
    "8575432": {
        'name': "Bay Bridge Air Gap",
        'lat': 38.9933,
        'lon': -76.3822,
        'state': 'MD',
        "Air Gap": "1",
        },
    "8575437": {
        'name': "Chesapeake Bay Bridge Visibility",
        'lat': 38.9948,
        'lon': -76.3881,
        'state': 'MD',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8575512": {
        'name': "Annapolis",
        'lat': 38.9833,
        'lon': -76.4816,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8577018": {
        'name': "Cove Point LNG Pier",
        'lat': 38.4044,
        'lon': -76.3855,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8577330": {
        'name': "Solomons Island",
        'lat': 38.3172,
        'lon': -76.4508,
        'state': 'MD',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8578240": {
        'name': "Piney Point",
        'lat': 38.1333,
        'lon': -76.5333,
        'state': 'MD',
        "Winds": "1",
        },
    "8594900": {
        'name': "Washington",
        'lat': 38.873,
        'lon': -77.0217,
        'state': 'DC',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8631044": {
        'name': "Wachapreague",
        'lat': 37.6078,
        'lon': -75.6858,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8632200": {
        'name': "Kiptopeke",
        'lat': 37.1652,
        'lon': -75.9884,
        'state': 'VA',
        "Water Level": "1",
        "Winds": "1",
        "Water Temp": "1",
        },
    "8632837": {
        'name': "Rappahannock Light",
        'lat': 37.5383,
        'lon': -76.015,
        'state': 'VA',
        "Winds": "1",
        "Air Pressure": "1",
        },
    "8635027": {
        'name': "Dahlgren",
        'lat': 38.32,
        'lon': -77.0367,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8635750": {
        'name': "Lewisetta",
        'lat': 37.9953,
        'lon': -76.4647,
        'state': 'VA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8636580": {
        'name': "Windmill Point",
        'lat': 37.6162,
        'lon': -76.29,
        'state': 'VA',
        "Water Level": "1",
        },
    "8637611": {
        'name': "York River East Rear Range Light",
        'lat': 37.25,
        'lon': -76.3,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "0",
        },
    "8637689": {
        'name': "Yorktown USCG Training Center",
        'lat': 37.2265,
        'lon': -76.4788,
        'state': 'VA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8638511": {
        'name': "Dominion Terminal Associates",
        'lat': 36.9623,
        'lon': -76.4242,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8638595": {
        'name': "South Craney Island",
        'lat': 36.9,
        'lon': -76.3386,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8638610": {
        'name': "Sewells Point",
        'lat': 36.9467,
        'lon': -76.33,
        'state': 'VA',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8638614": {
        'name': "Willoughby Degaussing Station",
        'lat': 36.9817,
        'lon': -76.3217,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8638901": {
        'name': "CBBT, Chesapeake Channel",
        'lat': 37.0329,
        'lon': -76.0833,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8638999": {
        'name': "Cape Henry",
        'lat': 36.93,
        'lon': -76.0067,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8639348": {
        'name': "Money Point",
        'lat': 36.7783,
        'lon': -76.3017,
        'state': 'VA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Water Level": "1",
        },
    "8651370": {
        'name': "Duck",
        'lat': 36.1833,
        'lon': -75.7467,
        'state': 'NC',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8652587": {
        'name': "Oregon Inlet Marina",
        'lat': 35.795,
        'lon': -75.5481,
        'state': 'NC',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8654467": {
        'name': "USCG Station Hatteras",
        'lat': 35.2086,
        'lon': -75.7042,
        'state': 'NC',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8656483": {
        'name': "Beaufort, Duke Marine Lab",
        'lat': 34.72,
        'lon': -76.67,
        'state': 'NC',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8658120": {
        'name': "Wilmington",
        'lat': 34.2275,
        'lon': -77.9536,
        'state': 'NC',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8658163": {
        'name': "Wrightsville Beach",
        'lat': 34.2133,
        'lon': -77.7867,
        'state': 'NC',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8661070": {
        'name': "Springmaid Pier",
        'lat': 33.655,
        'lon': -78.9183,
        'state': 'SC',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8662245": {
        'name': "Oyster Landing (N Inlet Estuary)",
        'lat': 33.3517,
        'lon': -79.1867,
        'state': 'SC',
        "Water Level": "0",
        },
    "8664753": {
        'name': "Don Holt Bridge Air Gap",
        'lat': 32.8912,
        'lon': -79.9644,
        'state': 'SC',
        "Air Gap": "1",
        },
    "8665353": {
        'name': "Ravenel Bridge Air Gap",
        'lat': 32.8031,
        'lon': -79.9139,
        'state': 'SC',
        "Air Gap": "1",
        },
    "8665530": {
        'name': "Charleston, Cooper River Entrance",
        'lat': 32.7808,
        'lon': -79.9236,
        'state': 'SC',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8670674": {
        'name': "Talmadge Memorial Bridge Air Gap",
        'lat': 32.0883,
        'lon': -81.099,
        'state': 'GA',
        "Air Gap": "1",
        },
    "8670870": {
        'name': "Fort Pulaski",
        'lat': 32.0367,
        'lon': -80.9017,
        'state': 'GA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8720030": {
        'name': "Fernandina Beach",
        'lat': 30.6714,
        'lon': -81.4658,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8720215": {
        'name': "Navy Fuel Depot",
        'lat': 30.4,
        'lon': -81.6267,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8720218": {
        'name': "Mayport (Bar Pilots Dock)",
        'lat': 30.3982,
        'lon': -81.4279,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "0",
        },
    "8720219": {
        'name': "Dames Point",
        'lat': 30.3872,
        'lon': -81.5592,
        'state': 'FL',
        "Water Level": "1",
        "Water Temp": "1",
        "Conductivity": "1",
        },
    "8720226": {
        'name': "Southbank Riverwalk, St Johns River",
        'lat': 30.3205,
        'lon': -81.6591,
        'state': 'FL',
        "Water Level": "1",
        },
    "8720228": {
        'name': "Little Jetties Visibility",
        'lat': 30.3794,
        'lon': -81.4461,
        'state': 'FL',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8720233": {
        'name': "Blount Island Command",
        'lat': 30.3925,
        'lon': -81.5225,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "0",
        "Humidity": "1",
        },
    "8720245": {
        'name': "Jacksonville University",
        'lat': 30.3541,
        'lon': -81.6118,
        'state': 'FL',
        "Water Temp": "1",
        "Conductivity": "1",
        },
    "8720357": {
        'name': "I-295 Buckman Bridge",
        'lat': 30.1924,
        'lon': -81.69,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8720376": {
        'name': "Dames Point Bridge Air Gap",
        'lat': 30.3845,
        'lon': -81.5571,
        'state': 'FL',
        "Air Gap": "1",
        },
    "8721604": {
        'name': "Trident Pier, Port Canaveral",
        'lat': 28.4158,
        'lon': -80.5931,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8722670": {
        'name': "Lake Worth Pier, Atlantic Ocean",
        'lat': 26.6128,
        'lon': -80.0342,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8722956": {
        'name': "South Port Everglades",
        'lat': 26.0817,
        'lon': -80.1167,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8723214": {
        'name': "Virginia Key, Biscayne Bay",
        'lat': 25.7317,
        'lon': -80.1617,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8723970": {
        'name': "Vaca Key, Florida Bay",
        'lat': 24.711,
        'lon': -81.1065,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8724580": {
        'name': "Key West",
        'lat': 24.5508,
        'lon': -81.8081,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "0",
        "Water Level": "1",
        },
    "8725110": {
        'name': "Naples, Gulf of Mexico",
        'lat': 26.1317,
        'lon': -81.8075,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8725520": {
        'name': "Fort Myers",
        'lat': 26.648,
        'lon': -81.871,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8726371": {
        'name': "Sunshine Skyway Bridge Air Gap",
        'lat': 27.6206,
        'lon': -82.6558,
        'state': 'FL',
        "Air Gap": "1",
        },
    "8726384": {
        'name': "Port Manatee",
        'lat': 27.6383,
        'lon': -82.5625,
        'state': 'FL',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8726412": {
        'name': "Middle Tampa Bay",
        'lat': 27.6617,
        'lon': -82.5994,
        'state': '',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8726520": {
        'name': "St. Petersburg, Tampa Bay",
        'lat': 27.7606,
        'lon': -82.6269,
        'state': 'FL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8726524": {
        'name': "Gadsden Cut, Tampa Bay",
        'lat': 27.7735,
        'lon': -82.5169,
        'state': 'FL',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8726607": {
        'name': "Old Port Tampa",
        'lat': 27.8578,
        'lon': -82.5528,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8726671": {
        'name': "Sparkman Channel Entrance",
        'lat': 27.9206,
        'lon': -82.4453,
        'state': 'FL',
        "Winds": "1",
        },
    "8726674": {
        'name': "East Bay",
        'lat': 27.9231,
        'lon': -82.4214,
        'state': 'FL',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8726679": {
        'name': "East Bay Causeway",
        'lat': 27.929,
        'lon': -82.4257,
        'state': 'FL',
        "Winds": "0",
        },
    "8726694": {
        'name': "TPA Cruise Terminal 2",
        'lat': 27.9333,
        'lon': -82.4333,
        'state': 'FL',
        "Winds": "0",
        },
    "8726724": {
        'name': "Clearwater Beach",
        'lat': 27.9783,
        'lon': -82.8317,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "0",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8727520": {
        'name': "Cedar Key",
        'lat': 29.135,
        'lon': -83.0317,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8728690": {
        'name': "Apalachicola",
        'lat': 29.7244,
        'lon': -84.9806,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8729108": {
        'name': "Panama City",
        'lat': 30.1523,
        'lon': -85.6669,
        'state': 'FL',
        "Winds": "1",
        "Water Temp": "0",
        "Water Level": "1",
        },
    "8729210": {
        'name': "Panama City Beach",
        'lat': 30.2133,
        'lon': -85.8783,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8729840": {
        'name': "Pensacola",
        'lat': 30.4044,
        'lon': -87.2112,
        'state': 'FL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8734536": {
        'name': "E Range Front Light Visibility",
        'lat': 30.44,
        'lon': -88.0096,
        'state': 'AL',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8734673": {
        'name': "Fort Morgan",
        'lat': 30.2283,
        'lon': -88.025,
        'state': 'AL',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "8735180": {
        'name': "Dauphin Island",
        'lat': 30.25,
        'lon': -88.075,
        'state': 'AL',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8735391": {
        'name': "Dog River Bridge",
        'lat': 30.5652,
        'lon': -88.088,
        'state': 'AL',
        "Water Level": "1",
        },
    "8735523": {
        'name': "East Fowl River Bridge",
        'lat': 30.4437,
        'lon': -88.1139,
        'state': 'AL',
        "Water Level": "1",
        },
    "8736163": {
        'name': "Middle Bay Port Visibility,  Mobile Bay",
        'lat': 30.5272,
        'lon': -88.0861,
        'state': 'AL',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8736897": {
        'name': "Coast Guard Sector Mobile",
        'lat': 30.6483,
        'lon': -88.0583,
        'state': 'AL',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8737005": {
        'name': "Pinto Island Visibility",
        'lat': 30.6712,
        'lon': -88.031,
        'state': 'AL',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8737048": {
        'name': "Mobile State Docks",
        'lat': 30.7046,
        'lon': -88.0396,
        'state': 'AL',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "8737138": {
        'name': "Chickasaw Creek",
        'lat': 30.7819,
        'lon': -88.0736,
        'state': 'AL',
        "Water Level": "1",
        },
    "8738043": {
        'name': "West Fowl River Bridge",
        'lat': 30.3766,
        'lon': -88.1586,
        'state': 'AL',
        "Water Level": "1",
        },
    "8739803": {
        'name': "Bayou La Batre Bridge",
        'lat': 30.4062,
        'lon': -88.2478,
        'state': 'AL',
        "Water Level": "1",
        },
    "8741003": {
        'name': "Petit Bois Island, Port of Pascagoula",
        'lat': 30.2133,
        'lon': -88.5,
        'state': 'MS',
        "Winds": "1",
        "Air Temp": "0",
        "Air Pressure": "1",
        },
    "8741533": {
        'name': "Pascagoula NOAA Lab",
        'lat': 30.3678,
        'lon': -88.5631,
        'state': 'MS',
        "Water Level": "1",
        "Water Temp": "1",
        },
    "8747437": {
        'name': "Bay Waveland Yacht Club",
        'lat': 30.325,
        'lon': -89.325,
        'state': 'MS',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8760721": {
        'name': "Pilottown",
        'lat': 29.1783,
        'lon': -89.2583,
        'state': 'LA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8760922": {
        'name': "Pilots Station East, S.W. Pass",
        'lat': 28.9322,
        'lon': -89.4075,
        'state': 'LA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8761305": {
        'name': "Shell Beach",
        'lat': 29.8683,
        'lon': -89.673,
        'state': 'LA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8761724": {
        'name': "Grand Isle",
        'lat': 29.263,
        'lon': -89.957,
        'state': 'LA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8761847": {
        'name': "Crescent City Air Gap",
        'lat': 29.9383,
        'lon': -90.0572,
        'state': 'LA',
        "Air Gap": "1",
        },
    "8761927": {
        'name': "New Canal Station",
        'lat': 30.0272,
        'lon': -90.1133,
        'state': 'LA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8761955": {
        'name': "Carrollton",
        'lat': 29.9329,
        'lon': -90.1355,
        'state': 'LA',
        "Water Level": "1",
        "Water Temp": "1",
        },
    "8762002": {
        'name': "Huey lon Bridge Air Gap",
        'lat': 29.9431,
        'lon': -90.1681,
        'state': '',
        "Air Gap": "1",
        },
    "8762075": {
        'name': "Port Fourchon, Belle Pass",
        'lat': 29.1142,
        'lon': -90.1992,
        'state': 'LA',
        "Water Level": "1",
        },
    "8762482": {
        'name': "West Bank 1, Bayou Gauche",
        'lat': 29.7886,
        'lon': -90.4203,
        'state': 'LA',
        "Winds": "0",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8762483": {
        'name': "I-10 Bonnet Carre Floodway",
        'lat': 30.0679,
        'lon': -90.39,
        'state': '',
        "Water Level": "0",
        },
    "8762484": {
        'name': "Frenier Landing",
        'lat': 30.1057,
        'lon': -90.4225,
        'state': 'LA',
        "Winds": "0",
        "Air Temp": "0",
        "Air Pressure": "0",
        "Humidity": "0",
        },
    "8764044": {
        'name': "Berwick, Atchafalaya River",
        'lat': 29.6675,
        'lon': -91.2376,
        'state': 'LA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8764227": {
        'name': "LAWMA, Amerada Pass",
        'lat': 29.4496,
        'lon': -91.3381,
        'state': 'LA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8764314": {
        'name': "Eugene Island, North of, Atchafalaya Bay",
        'lat': 29.3675,
        'lon': -91.3839,
        'state': '',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "0",
        "Humidity": "1",
        "Water Level": "1",
        },
    "8766072": {
        'name': "Freshwater Canal Locks",
        'lat': 29.5517,
        'lon': -92.3052,
        'state': 'LA',
        "Winds": "0",
        "Water Level": "1",
        },
    "8767816": {
        'name': "Lake Charles",
        'lat': 30.2236,
        'lon': -93.2217,
        'state': 'LA',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8767931": {
        'name': "Lake Charles I-210 Bridge Air Gap",
        'lat': 30.2017,
        'lon': -93.2806,
        'state': 'LA',
        "Air Gap": "1",
        },
    "8767961": {
        'name': "Bulk Terminal",
        'lat': 30.1903,
        'lon': -93.3007,
        'state': 'LA',
        "Water Level": "1",
        "Water Temp": "1",
        },
    "8768094": {
        'name': "Calcasieu Pass",
        'lat': 29.7682,
        'lon': -93.3429,
        'state': 'LA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8770475": {
        'name': "Port Arthur",
        'lat': 29.8671,
        'lon': -93.931,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8770520": {
        'name': "Rainbow Bridge",
        'lat': 29.98,
        'lon': -93.8817,
        'state': 'TX',
        "Water Level": "1",
        },
    "8770613": {
        'name': "Morgans Point, Barbours Cut",
        'lat': 29.6817,
        'lon': -94.985,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Water Level": "1",
        },
    "8770777": {
        'name': "Manchester",
        'lat': 29.7262,
        'lon': -95.2658,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8770808": {
        'name': "High Island",
        'lat': 29.5947,
        'lon': -94.3903,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8770822": {
        'name': "Texas Point, Sabine Pass",
        'lat': 29.6894,
        'lon': -93.8419,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8770971": {
        'name': "Rollover Pass",
        'lat': 29.515,
        'lon': -94.513,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8771013": {
        'name': "Eagle Point, Galveston Bay",
        'lat': 29.48,
        'lon': -94.9183,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        "Water Level": "1",
        },
    "8771341": {
        'name': "Galveston Bay Entrance, North Jetty",
        'lat': 29.3573,
        'lon': -94.7248,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8771367": {
        'name': "Sabine Offshore Light",
        'lat': 29.469,
        'lon': -93.72,
        'state': '',
        "Water Level": "1",
        },
    "8771450": {
        'name': "Galveston Pier 21",
        'lat': 29.31,
        'lon': -94.7933,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8771486": {
        'name': "Galveston Railroad Bridge",
        'lat': 29.3026,
        'lon': -94.8971,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8771972": {
        'name': "San Luis Pass",
        'lat': 29.0806,
        'lon': -95.1308,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8772471": {
        'name': "Freeport Harbor",
        'lat': 28.9357,
        'lon': -95.2942,
        'state': '',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8772985": {
        'name': "Sargent",
        'lat': 28.7714,
        'lon': -95.6172,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8773037": {
        'name': "Seadrift",
        'lat': 28.4069,
        'lon': -96.7124,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8773146": {
        'name': "Matagorda City",
        'lat': 28.7101,
        'lon': -95.914,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8773259": {
        'name': "Port Lavaca",
        'lat': 28.6406,
        'lon': -96.6098,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8773701": {
        'name': "Port O'Connor",
        'lat': 28.4459,
        'lon': -96.3956,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8773767": {
        'name': "Matagorda Bay Entrance Channel",
        'lat': 28.4269,
        'lon': -96.3301,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8774230": {
        'name': "Aransas Wildlife Refuge",
        'lat': 28.2283,
        'lon': -96.795,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8774770": {
        'name': "Rockport",
        'lat': 28.0217,
        'lon': -97.0467,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8775132": {
        'name': "La Quinta Channel North",
        'lat': 27.8792,
        'lon': -97.2861,
        'state': '',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "8775222": {
        'name': "Viola Turning Basin",
        'lat': 27.8461,
        'lon': -97.5208,
        'state': '',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "8775223": {
        'name': "Harbor Island Visibility",
        'lat': 27.844,
        'lon': -97.0696,
        'state': 'TX',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8775236": {
        'name': "UTMSI Visibility",
        'lat': 27.8383,
        'lon': -97.0522,
        'state': 'TX',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8775237": {
        'name': "Port Aransas",
        'lat': 27.8397,
        'lon': -97.0725,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8775241": {
        'name': "Aransas, Aransas Pass",
        'lat': 27.8366,
        'lon': -97.0391,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8775244": {
        'name': "Nueces Bay",
        'lat': 27.8328,
        'lon': -97.4859,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        },
    "8775283": {
        'name': "Enbridge, Ingleside",
        'lat': 27.8217,
        'lon': -97.2033,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        "Water Level": "0",
        },
    "8775285": {
        'name': "Tule Lake Visibility",
        'lat': 27.8194,
        'lon': -97.4537,
        'state': 'TX',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8775296": {
        'name': "USS Lexington, Corpus Christi Bay",
        'lat': 27.8117,
        'lon': -97.39,
        'state': 'TX',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8775302": {
        'name': "Texas State Aquarium Visibility",
        'lat': 27.8125,
        'lon': -97.3886,
        'state': 'TX',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "8775792": {
        'name': "Packery Channel",
        'lat': 27.6342,
        'lon': -97.2361,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8775870": {
        'name': "Bob Hall Pier, Corpus Christi",
        'lat': 27.5808,
        'lon': -97.2164,
        'state': 'TX',
        "Winds": "0",
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Water Level": "0",
        },
    "8776139": {
        'name': "S. Bird Island",
        'lat': 27.4844,
        'lon': -97.3181,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8776604": {
        'name': "Baffin Bay",
        'lat': 27.297,
        'lon': -97.4052,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8777812": {
        'name': "Rincon Del San Jose",
        'lat': 26.8012,
        'lon': -97.4706,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8778490": {
        'name': "Port Mansfield",
        'lat': 26.5576,
        'lon': -97.4257,
        'state': 'TX',
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8779280": {
        'name': "Realitos Peninsula",
        'lat': 26.2625,
        'lon': -97.2853,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8779748": {
        'name': "South Padre Island CG Station",
        'lat': 26.0725,
        'lon': -97.1669,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "8779749": {
        'name': "SPI Brazos Santiago",
        'lat': 26.0675,
        'lon': -97.1547,
        'state': 'TX',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "8779770": {
        'name': "Port Isabel",
        'lat': 26.0612,
        'lon': -97.2155,
        'state': 'TX',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9014070": {
        'name': "Algonac",
        'lat': 42.6211,
        'lon': -82.5267,
        'state': 'MI',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9014080": {
        'name': "St. Clair State Police",
        'lat': 42.8122,
        'lon': -82.4856,
        'state': 'MI',
        "Water Level": "1",
        },
    "9014087": {
        'name': "Dry Dock",
        'lat': 42.9453,
        'lon': -82.4433,
        'state': 'MI',
        "Water Level": "1",
        },
    "9014090": {
        'name': "Mouth of the Black River",
        'lat': 42.9747,
        'lon': -82.4189,
        'state': 'MI',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9014096": {
        'name': "Dunn Paper",
        'lat': 43.0033,
        'lon': -82.4217,
        'state': 'MI',
        "Water Level": "1",
        },
    "9014098": {
        'name': "Fort Gratiot",
        'lat': 43.0069,
        'lon': -82.4225,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9034052": {
        'name': "St Clair Shores",
        'lat': 42.4732,
        'lon': -82.8792,
        'state': 'MI',
        "Water Level": "1",
        },
    "9044020": {
        'name': "Gibraltar",
        'lat': 42.0917,
        'lon': -83.1867,
        'state': 'MI',
        "Water Level": "1",
        },
    "9044030": {
        'name': "Wyandotte",
        'lat': 42.2023,
        'lon': -83.1475,
        'state': 'MI',
        "Water Level": "1",
        },
    "9044036": {
        'name': "Fort Wayne",
        'lat': 42.2989,
        'lon': -83.0926,
        'state': 'MI',
        "Water Level": "1",
        },
    "9044049": {
        'name': "Windmill Point",
        'lat': 42.3575,
        'lon': -82.93,
        'state': 'MI',
        "Water Level": "1",
        },
    "9052000": {
        'name': "Cape Vincent",
        'lat': 44.1303,
        'lon': -76.332,
        'state': 'NY',
        "Water Level": "1",
        },
    "9052030": {
        'name': "Oswego",
        'lat': 43.4642,
        'lon': -76.5118,
        'state': 'NY',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9052058": {
        'name': "Rochester",
        'lat': 43.269,
        'lon': -77.6257,
        'state': 'NY',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9052076": {
        'name': "Olcott",
        'lat': 43.3384,
        'lon': -78.7273,
        'state': 'NY',
        "Water Level": "1",
        },
    "9063007": {
        'name': "Ashland Ave",
        'lat': 43.1,
        'lon': -79.0599,
        'state': 'NY',
        "Water Level": "1",
        },
    "9063009": {
        'name': "American Falls",
        'lat': 43.0811,
        'lon': -79.0614,
        'state': 'NY',
        "Water Level": "1",
        },
    "9063012": {
        'name': "Niagara Intake",
        'lat': 43.0769,
        'lon': -79.0139,
        'state': 'NY',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9063020": {
        'name': "Buffalo",
        'lat': 42.8774,
        'lon': -78.8905,
        'state': 'NY',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9063028": {
        'name': "Sturgeon Point",
        'lat': 42.6913,
        'lon': -79.0473,
        'state': 'NY',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9063038": {
        'name': "Erie, Lake Erie",
        'lat': 42.1539,
        'lon': -80.0758,
        'state': 'PA',
        "Winds": "1",
        "Water Level": "1",
        },
    "9063053": {
        'name': "Fairport",
        'lat': 41.7597,
        'lon': -81.2811,
        'state': 'OH',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9063063": {
        'name': "Cleveland",
        'lat': 41.5409,
        'lon': -81.6355,
        'state': 'OH',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9063079": {
        'name': "Marblehead",
        'lat': 41.5436,
        'lon': -82.7314,
        'state': 'OH',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9063085": {
        'name': "Toledo",
        'lat': 41.6936,
        'lon': -83.4723,
        'state': 'OH',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9063090": {
        'name': "Fermi Power Plant",
        'lat': 41.96,
        'lon': -83.257,
        'state': 'MI',
        "Water Level": "1",
        },
    "9075002": {
        'name': "Lakeport",
        'lat': 43.1417,
        'lon': -82.4933,
        'state': 'MI',
        "Water Level": "1",
        },
    "9075014": {
        'name': "Harbor Beach",
        'lat': 43.8464,
        'lon': -82.6431,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9075035": {
        'name': "Essexville",
        'lat': 43.6404,
        'lon': -83.8468,
        'state': 'MI',
        "Water Level": "1",
        },
    "9075065": {
        'name': "Alpena",
        'lat': 45.063,
        'lon': -83.4286,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9075080": {
        'name': "Mackinaw City",
        'lat': 45.8,
        'lon': -84.7211,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9075099": {
        'name': "De Tour Village",
        'lat': 45.9925,
        'lon': -83.8982,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9076024": {
        'name': "Rock Cut",
        'lat': 46.2648,
        'lon': -84.1912,
        'state': 'MI',
        "Winds": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9076027": {
        'name': "West Neebish Island",
        'lat': 46.2833,
        'lon': -84.205,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9076033": {
        'name': "Little Rapids",
        'lat': 46.4858,
        'lon': -84.3017,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9076060": {
        'name': "U.S. Slip",
        'lat': 46.5008,
        'lon': -84.3404,
        'state': 'MI',
        "Water Level": "1",
        },
    "9076070": {
        'name': "S.W. Pier, St. Marys River",
        'lat': 46.5011,
        'lon': -84.3726,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9087023": {
        'name': "Ludington",
        'lat': 43.9474,
        'lon': -86.4416,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9087031": {
        'name': "Holland",
        'lat': 42.7733,
        'lon': -86.2128,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9087044": {
        'name': "Calumet Harbor",
        'lat': 41.7297,
        'lon': -87.5383,
        'state': 'IL',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9087057": {
        'name': "Milwaukee",
        'lat': 43.002,
        'lon': -87.8876,
        'state': 'WI',
        "Water Level": "1",
        },
    "9087068": {
        'name': "Kewaunee, Lake Michigan",
        'lat': 44.464,
        'lon': -87.501,
        'state': 'WI',
        "Water Level": "1",
        },
    "9087069": {
        'name': "Kewaunee MET",
        'lat': 44.465,
        'lon': -87.4958,
        'state': 'WI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9087072": {
        'name': "Sturgeon Bay Canal",
        'lat': 44.7956,
        'lon': -87.3143,
        'state': 'WI',
        "Water Level": "1",
        },
    "9087077": {
        'name': "Green Bay East",
        'lat': 44.5392,
        'lon': -88.001,
        'state': 'WI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9087088": {
        'name': "Menominee",
        'lat': 45.0959,
        'lon': -87.5899,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9087096": {
        'name': "Port Inland",
        'lat': 45.9699,
        'lon': -85.8715,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9099004": {
        'name': "Point Iroquois",
        'lat': 46.4845,
        'lon': -84.6309,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9099018": {
        'name': "Marquette C.G.",
        'lat': 46.5456,
        'lon': -87.3786,
        'state': 'MI',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9099044": {
        'name': "Ontonagon",
        'lat': 46.8744,
        'lon': -89.3242,
        'state': 'MI',
        "Water Level": "1",
        },
    "9099064": {
        'name': "Duluth",
        'lat': 46.7758,
        'lon': -92.092,
        'state': 'MN',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9099090": {
        'name': "Grand Marais, Lake Superior",
        'lat': 47.7486,
        'lon': -90.3413,
        'state': 'MN',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Humidity": "1",
        "Water Level": "1",
        },
    "9410170": {
        'name': "San Diego, San Diego Bay",
        'lat': 32.7142,
        'lon': -117.1736,
        'state': 'CA',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9410230": {
        'name': "La Jolla",
        'lat': 32.8669,
        'lon': -117.2571,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9410647": {
        'name': "Angels Gate",
        'lat': 33.7158,
        'lon': -118.2461,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9410660": {
        'name': "Los Angeles",
        'lat': 33.7199,
        'lon': -118.2729,
        'state': 'CA',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9410665": {
        'name': "Los Angeles Pier J",
        'lat': 33.733,
        'lon': -118.1857,
        'state': 'CA',
        "Winds": "1",
        },
    "9410666": {
        'name': "Los Angeles Pier 400",
        'lat': 33.7352,
        'lon': -118.2413,
        'state': 'CA',
        "Winds": "1",
        },
    "9410670": {
        'name': "Los Angeles Pier F",
        'lat': 33.7463,
        'lon': -118.2156,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9410676": {
        'name': "Vincent Thomas Bridge Air Gap",
        'lat': 33.7494,
        'lon': -118.2714,
        'state': 'CA',
        "Air Gap": "1",
        },
    "9410689": {
        'name': "Gerald Desmond Bridge Air Gap",
        'lat': 33.7645,
        'lon': -118.221,
        'state': 'CA',
        "Air Gap": "1",
        },
    "9410690": {
        'name': "Los Angeles Berth 161",
        'lat': 33.7636,
        'lon': -118.2654,
        'state': 'CA',
        "Winds": "1",
        },
    "9410691": {
        'name': "Los Angeles Badger Avenue Bridge",
        'lat': 33.7663,
        'lon': -118.2401,
        'state': 'CA',
        "Winds": "1",
        },
    "9410692": {
        'name': "Los Angeles Pier S",
        'lat': 33.7683,
        'lon': -118.2257,
        'state': 'CA',
        "Winds": "0",
        },
    "9410840": {
        'name': "Santa Monica",
        'lat': 34.0083,
        'lon': -118.5,
        'state': 'CA',
        "Winds": "0",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9411340": {
        'name': "Santa Barbara",
        'lat': 34.4031,
        'lon': -119.6928,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9411406": {
        'name': "Oil Platform Harvest",
        'lat': 34.4692,
        'lon': -120.6819,
        'state': 'CA',
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9412110": {
        'name': "Port San Luis",
        'lat': 35.1688,
        'lon': -120.7542,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9413450": {
        'name': "Monterey",
        'lat': 36.605,
        'lon': -121.8881,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9414290": {
        'name': "San Francisco",
        'lat': 37.8063,
        'lon': -122.4659,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9414296": {
        'name': "Pier 17 Visibility, San Francisco Bay",
        'lat': 37.803,
        'lon': -122.3971,
        'state': 'CA',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "1",
        },
    "9414304": {
        'name': "San Francisco-Oakland Bay Bridge Air Gap",
        'lat': 37.8044,
        'lon': -122.3728,
        'state': 'CA',
        "Air Gap": "1",
        },
    "9414311": {
        'name': "San Francisco Pier 1",
        'lat': 37.798,
        'lon': -122.393,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9414523": {
        'name': "Redwood City",
        'lat': 37.5067,
        'lon': -122.21,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9414750": {
        'name': "Alameda",
        'lat': 37.7717,
        'lon': -122.3,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9414763": {
        'name': "Oakland Berth 67",
        'lat': 37.795,
        'lon': -122.283,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9414769": {
        'name': "Oakland Middle Harbor",
        'lat': 37.8006,
        'lon': -122.3297,
        'state': 'CA',
        "Winds": "1",
        },
    "9414776": {
        'name': "Oakland Berth 34",
        'lat': 37.8106,
        'lon': -122.3,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9414797": {
        'name': "Oakland Berth 38 Visibility",
        'lat': 37.804,
        'lon': -122.3417,
        'state': 'CA',
        "Air Temp": "1",
        "Visibility": "1",
        "Humidity": "0",
        },
    "9414847": {
        'name': "Point Potrero Richmond",
        'lat': 37.9058,
        'lon': -122.365,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9414863": {
        'name': "Richmond",
        'lat': 37.923,
        'lon': -122.4096,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9415020": {
        'name': "Point Reyes",
        'lat': 37.9942,
        'lon': -122.9736,
        'state': 'CA',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9415102": {
        'name': "Martinez-Amorco Pier",
        'lat': 38.0346,
        'lon': -122.1252,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Visibility": "1",
        "Humidity": "0",
        "Water Level": "1",
        },
    "9415115": {
        'name': "Pittsburg, Suisun Bay",
        'lat': 38.0416,
        'lon': -121.887,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9415118": {
        'name': "Union Pacific Rail Road Bridge",
        'lat': 38.0383,
        'lon': -122.1205,
        'state': 'CA',
        "Winds": "1",
        },
    "9415141": {
        'name': "Davis Point",
        'lat': 38.0567,
        'lon': -122.2596,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        },
    "9415144": {
        'name': "Port Chicago",
        'lat': 38.056,
        'lon': -122.0395,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9416841": {
        'name': "Arena Cove",
        'lat': 38.9146,
        'lon': -123.7111,
        'state': 'CA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9418767": {
        'name': "North Spit",
        'lat': 40.7663,
        'lon': -124.2172,
        'state': 'CA',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9418768": {
        'name': "North Jetty Landing, Humboldt Bay",
        'lat': 40.7689,
        'lon': -124.239,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        },
    "9419750": {
        'name': "Crescent City",
        'lat': 41.7456,
        'lon': -124.1844,
        'state': 'CA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9431647": {
        'name': "Port Orford",
        'lat': 42.739,
        'lon': -124.4983,
        'state': 'OR',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9432780": {
        'name': "Charleston",
        'lat': 43.345,
        'lon': -124.322,
        'state': 'OR',
        "Water Level": "1",
        "Winds": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9435380": {
        'name': "South Beach",
        'lat': 44.6254,
        'lon': -124.0449,
        'state': 'OR',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9437540": {
        'name': "Garibaldi",
        'lat': 45.5545,
        'lon': -123.9189,
        'state': 'OR',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9439040": {
        'name': "Astoria",
        'lat': 46.2073,
        'lon': -123.7683,
        'state': 'OR',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9439099": {
        'name': "Wauna",
        'lat': 46.1617,
        'lon': -123.4089,
        'state': 'OR',
        "Water Level": "1",
        },
    "9439201": {
        'name': "St Helens",
        'lat': 45.8633,
        'lon': -122.7962,
        'state': 'OR',
        "Water Level": "1",
        },
    "9440083": {
        'name': "Vancouver",
        'lat': 45.6317,
        'lon': -122.697,
        'state': 'WA',
        "Water Level": "1",
        },
    "9440422": {
        'name': "lonview",
        'lat': 46.1061,
        'lon': -122.9542,
        'state': 'WA',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9440569": {
        'name': "Skamokawa",
        'lat': 46.2703,
        'lon': -123.4565,
        'state': 'WA',
        "Water Level": "1",
        },
    "9440581": {
        'name': "Cape Disappointment",
        'lat': 46.281,
        'lon': -124.0463,
        'state': 'WA',
        "Water Level": "1",
        },
    "9440910": {
        'name': "Toke Point",
        'lat': 46.7075,
        'lon': -123.9669,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9441102": {
        'name': "Westport",
        'lat': 46.9043,
        'lon': -124.1051,
        'state': 'WA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9442396": {
        'name': "La Push, Quillayute River",
        'lat': 47.913,
        'lon': -124.6369,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9443090": {
        'name': "Neah Bay",
        'lat': 48.3703,
        'lon': -124.6019,
        'state': 'WA',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9444090": {
        'name': "Port Angeles",
        'lat': 48.125,
        'lon': -123.44,
        'state': 'WA',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9444900": {
        'name': "Port Townsend",
        'lat': 48.1129,
        'lon': -122.7595,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9445958": {
        'name': "Bremerton",
        'lat': 47.5617,
        'lon': -122.623,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9446482": {
        'name': "Tacoma MET",
        'lat': 47.276,
        'lon': -122.418,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        },
    "9446484": {
        'name': "Tacoma",
        'lat': 47.27,
        'lon': -122.413,
        'state': 'WA',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9447130": {
        'name': "Seattle",
        'lat': 47.6019,
        'lon': -122.3392,
        'state': 'WA',
        "Water Level": "1",
        },
    "9449419": {
        'name': "Cherry Point South Dock",
        'lat': 48.86,
        'lon': -122.755,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        },
    "9449424": {
        'name': "Cherry Point",
        'lat': 48.8633,
        'lon': -122.758,
        'state': 'WA',
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9449427": {
        'name': "Cherry Point North Dock",
        'lat': 48.8642,
        'lon': -122.7642,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        },
    "9449880": {
        'name': "Friday Harbor",
        'lat': 48.5467,
        'lon': -123.01,
        'state': 'WA',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9450460": {
        'name': "Ketchikan",
        'lat': 55.3319,
        'lon': -131.6261,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9451054": {
        'name': "Port Alexander",
        'lat': 56.2466,
        'lon': -134.6477,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9451600": {
        'name': "Sitka",
        'lat': 57.0517,
        'lon': -135.342,
        'state': 'AK',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9452210": {
        'name': "Juneau",
        'lat': 58.2988,
        'lon': -134.4106,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9452400": {
        'name': "Skagway, Taiya Inlet",
        'lat': 59.4508,
        'lon': -135.328,
        'state': 'AK',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9452634": {
        'name': "Elfin Cove",
        'lat': 58.1947,
        'lon': -136.3469,
        'state': 'AK',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9453220": {
        'name': "Yakutat, Yakutat Bay",
        'lat': 59.5483,
        'lon': -139.7331,
        'state': 'AK',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9454050": {
        'name': "Cordova",
        'lat': 60.5583,
        'lon': -145.755,
        'state': 'AK',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Conductivity": "1",
        },
    "9454240": {
        'name': "Valdez",
        'lat': 61.1242,
        'lon': -146.3631,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9455090": {
        'name': "Seward",
        'lat': 60.12,
        'lon': -149.4267,
        'state': 'AK',
        "Water Level": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9455500": {
        'name': "Seldovia",
        'lat': 59.4405,
        'lon': -151.7199,
        'state': 'AK',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9455760": {
        'name': "Nikiski",
        'lat': 60.6833,
        'lon': -151.3981,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9455920": {
        'name': "Anchorage",
        'lat': 61.2375,
        'lon': -149.8904,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9457292": {
        'name': "Kodiak Island",
        'lat': 57.7303,
        'lon': -152.5139,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9457804": {
        'name': "Alitak",
        'lat': 56.8974,
        'lon': -154.248,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9459450": {
        'name': "Sand Point",
        'lat': 55.3317,
        'lon': -160.5043,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9459881": {
        'name': "King Cove",
        'lat': 55.0599,
        'lon': -162.3261,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9461380": {
        'name': "Adak Island",
        'lat': 51.8633,
        'lon': -176.632,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9461710": {
        'name': "Atka",
        'lat': 52.2319,
        'lon': -174.1725,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9462450": {
        'name': "Nikolski",
        'lat': 52.9406,
        'lon': -168.8713,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9462620": {
        'name': "Unalaska",
        'lat': 53.8792,
        'lon': -166.5403,
        'state': 'AK',
        "Winds": "0",
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Water Level": "0",
        },
    "9463502": {
        'name': "Port Moller",
        'lat': 55.9858,
        'lon': -160.5736,
        'state': 'AK',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9464212": {
        'name': "Village Cove, St Paul Island",
        'lat': 57.1253,
        'lon': -170.2853,
        'state': 'AK',
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9468333": {
        'name': "Unalakleet",
        'lat': 63.8714,
        'lon': -160.7843,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9468756": {
        'name': "Nome, Norton Sound",
        'lat': 64.4946,
        'lon': -165.4396,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9491094": {
        'name': "Red Dog Dock",
        'lat': 67.5758,
        'lon': -164.0644,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9497645": {
        'name': "Prudhoe Bay",
        'lat': 70.4114,
        'lon': -148.5317,
        'state': 'AK',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9751364": {
        'name': "Christiansted Harbor, St Croix",
        'lat': 17.7477,
        'lon': -64.6984,
        'state': 'VI',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9751381": {
        'name': "Lameshur Bay, St John",
        'lat': 18.3182,
        'lon': -64.7242,
        'state': 'VI',
        "Water Level": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9751401": {
        'name': "Lime Tree Bay",
        'lat': 17.6947,
        'lon': -64.7538,
        'state': 'VI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9751639": {
        'name': "Charlotte Amalie",
        'lat': 18.3358,
        'lon': -64.92,
        'state': 'VI',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9752235": {
        'name': "Culebra",
        'lat': 18.3009,
        'lon': -65.3025,
        'state': 'PR',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9752619": {
        'name': "Isabel Segunda, Vieques Island",
        'lat': 18.1525,
        'lon': -65.4439,
        'state': 'PR',
        "Water Level": "0",
        "Winds": "0",
        "Air Temp": "0",
        },
    "9752695": {
        'name': "Esperanza, Vieques Island",
        'lat': 18.0939,
        'lon': -65.4714,
        'state': 'PR',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9753216": {
        'name': "Fajardo",
        'lat': 18.3353,
        'lon': -65.6311,
        'state': 'PR',
        "Water Level": "0",
        "Winds": "0",
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Humidity": "0",
        },
    "9754228": {
        'name': "Yabucoa Harbor",
        'lat': 18.0551,
        'lon': -65.833,
        'state': 'PR',
        "Water Level": "0",
        "Winds": "0",
        "Air Temp": "0",
        "Water Temp": "0",
        "Air Pressure": "0",
        "Humidity": "0",
        },
    "9755371": {
        'name': "San Juan, La Puntilla, San Juan Bay",
        'lat': 18.4592,
        'lon': -66.1164,
        'state': 'PR',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9757809": {
        'name': "Arecibo",
        'lat': 18.4805,
        'lon': -66.7024,
        'state': 'PR',
        "Water Level": "0",
        "Winds": "1",
        "Air Temp": "0",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9759110": {
        'name': "Magueyes Island",
        'lat': 17.9701,
        'lon': -67.0464,
        'state': 'PR',
        "Water Level": "1",
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        },
    "9759394": {
        'name': "Mayaguez",
        'lat': 18.2189,
        'lon': -67.1625,
        'state': 'PR',
        "Winds": "1",
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9759938": {
        'name': "Mona Island",
        'lat': 18.0899,
        'lon': -67.9385,
        'state': '',
        "Air Temp": "1",
        "Water Temp": "1",
        "Air Pressure": "1",
        "Water Level": "1",
        },
    "9761115": {
        'name': "Barbuda",
        'lat': 17.5908,
        'lon': -61.8206,
        'state': 'Antigua and Barbuda',
        "Winds": "0",
        "Air Temp": "1",
        "Water Temp": "0",
        "Air Pressure": "1",
        "Water Level": "0",
    }}